version: '3.4'

services:
  web:
    build:
      context: . 
      dockerfile: Dockerfile
    ports:
      - "2048:8080"
    depends_on:
      - db
        
  db:
    image: "postgres:13"
    environment:
      - POSTGRES_USER=noos
      - POSTGRES_PASSWORD=DatabasePassword123
      - POSTGRES_DB=aspnet-TengrehNoos-1
    ports:
      - "2049:2049"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
volumes:
  dbdata:
